### PR TITLE
ISSD-695 [PRM] Add "Title" field to Deal Reg

### PR DESCRIPTION
**Pull request by abfranca**

### CODE REVIEW

**Review by ryanschuhler — APPROVED** [review]
Looks good!

**Review by thaynam — APPROVED** [review]

**Comment by thaynam** [comment]
ci:forward:force

**Comment by thaynam** [comment]
ci:forward:force

**Comment by thaynam** [comment]
ci:forward:force

**Comment by thaynam** [comment]
ci:forward:force

**Comment by thaynam** [comment]
ci:forward:force

**Comment by thaynam** [comment]
ci:forward:force

**Pull request closed without merging**
