### PR TITLE
ISSD-4132 Link Home and Navigation Menu Capability Pages to its capability page and some minor CSS improvements

### PR DESCRIPTION
**Pull request by rtienpal**

### CODE REVIEW

**Comment by rtienpal** [comment]
ci:test:sf

**Review by ryanschuhler — APPROVED** [review]
Looks good!

**Comment by ryanschuhler** [comment]
ci:forward:force

**Comment by ryanschuhler** [comment]
thanks https://github.com/brianchandotcom/liferay-portal/pull/149580

**Pull request closed without merging**
