### PR TITLE
 ISSD-3152 [PRM] MDF Automated request close complete case

### PR DESCRIPTION
**Pull request by eliasantosf**
Task: [ISSD-3152](https://liferay.atlassian.net/browse/ISSD-3152)

### CODE REVIEW

**Comment by amosfong** [comment]
Hey Elias,

I made some changes:
-oauth scopes for objects are lowercase now
-updated resourcePath to match ObjectActionOrganizationStatusRestController
-update method name _completeMdfRequestStatus to be more descriptive
-Moved things around for better flow (some of it is preference)
-responseJSONObject.getString("externalReferenceCode") is the same as mdfRequestExternalReferenceCode right? I used the same var so it's clear they are the same thing.
-Why do we need to add the URL to liferay.oauth.urls.excludes? I dont see it done anywhere else?

https://github.com/liferay-customer-delivery/liferay-portal/pull/60

**Comment by eliasantosf** [comment]
Hi @amosfong, the URL can be removed from liferay.oauth.urls.excludes, I was putting it there to access the endpoint faster in the tests. But it's not necessary.

**Comment by amosfong** [comment]
ok great, I'll remove it then, thanks

**Comment by eliasantosf** [comment]
ci:reopen

**Pull request closed without merging**
