### PR TITLE
ISSD-3174 [PRM] Show required field validation when user's trying to proceed with deal registration form

### PR DESCRIPTION
**Pull request by thaynam**

### CODE REVIEW

**Comment by thaynam** [comment]
ci:forward:force

**Comment by thaynam** [comment]
ci:forward:force

**Comment by thaynam** [comment]
ci:test:sf

**Comment by jairmedeiros** [comment]
ci:forward:force

**Comment by jairmedeiros** [comment]
ci:forward:force

**Comment by thaynam** [comment]
ci:forward:force

**Pull request closed without merging**
