### PR TITLE
ISSD-4159 updates for liferay self-hosted

### PR DESCRIPTION
**Pull request by amosfong**

### CODE REVIEW

**Comment by amosfong** [comment]
@ryanschuhler , can you review, thanks!

**Review by ryanschuhler — APPROVED** [review]
This looks good. I thought the formatter would split that jsx line up, but it doesnt seem to care, and the logic all makes sense to me

**Comment by amosfong** [comment]
ci:forward:force

**Comment by amosfong** [comment]
ci:forward:foce

**Pull request closed without merging**
