### PR TITLE
ISSD-4110 [PRM] Aggregations indexing problem

### PR DESCRIPTION
**Pull request by eliasantosf**
Task: [ISSD-4110](https://liferay.atlassian.net/browse/ISSD-4110)

### CODE REVIEW

**Review by ryanschuhler — APPROVED** [review]
Looks good!

**Comment by eliasantosf** [comment]
@thaynam, the context was given to me in the bug ticket, can you take a look at it? https://liferay.atlassian.net/browse/ISSD-4106

**Comment by thaynam** [comment]
@eliasantosf @ryanschuhler FYI I talked with Abelenda about why this change needs to be done, he explained that the Aggregation fields do not work properly when we try to filter or search using them, and their related "children" objects, they had many problem using it extensively in Testray, so they decided to remove the indexing from it. We are forwarding this to prevent further problems.

**Review by thaynam — APPROVED** [review]

**Comment by thaynam** [comment]
ci:forward:force

**Pull request closed without merging**
