### PR TITLE
ISSD-3964 [CP 2.0] Fix reference error in the title of the key renewal flow

### PR DESCRIPTION
**Pull request by pedroliveirav**
[ISSD-3964](https://liferay.atlassian.net/browse/ISSD-3964)

### CODE REVIEW

**Review by kylembischof — APPROVED** [review]

**Comment by kylembischof** [comment]
ci:forward

**Comment by pedroliveirav** [comment]
ci:forward:force

**Comment by kylembischof** [comment]
ci:reevaluate:1327401_4104

**Comment by kylembischof** [comment]
ci:forward:force

**Pull request closed without merging**
