### PR TITLE
ISSD-4151 [PRM] [Impedibug] Request not completing on first update

### PR DESCRIPTION
**Pull request by eliasantosf**
Task: [ISSD-4151](https://liferay.atlassian.net/browse/ISSD-4151)

### CODE REVIEW

**Review by thaynam — APPROVED** [review]

**Comment by thaynam** [comment]
ci:forward

**Review by ryanschuhler — APPROVED** [review]
👍

**Review by amosfong — APPROVED** [review]

**Comment by eliasantosf** [comment]
ci:forward:force

**Comment by eliasantosf** [comment]
Related to: https://github.com/brianchandotcom/liferay-portal/pull/149619

**Comment by eliasantosf** [comment]
ci:close

**Pull request closed without merging**
