### PR TITLE
ISSUP-3068 Onboarding forms are not working

### PR DESCRIPTION
**Pull request by amosfong**
caused by variable name rename in https://liferay.atlassian.net/browse/ISSD-2213

### CODE REVIEW

**Comment by amosfong** [comment]
@jennyhchen fyi

**Comment by amosfong** [comment]
@jennyhchen you added more logic related to this ticket? or for something else?

**Comment by jennyhchen** [comment]
just to clean it up a bit so I pulled this commit to avoid merge conflicts, if I add anything, I'll be sure to update the onboarding/index.jsx as well to make sure it's consistent

**Review by jairmedeiros — APPROVED** [review]

**Comment by kylembischof** [comment]
ci:forward

**Comment by amosfong** [comment]
ci:forward

**Comment by amosfong** [comment]
Fixed the commit message

**Pull request closed without merging**
