### PR TITLE
ISSD-3033 [CP 2.0] Update CP home page's help button

### PR DESCRIPTION
**Pull request by samuelleolopes**
[ISSD-3033](https://liferay.atlassian.net/browse/ISSD-3033)

### CODE REVIEW

**Comment by kylembischof** [comment]
is the old text "Watch Tutorial Videos" still used anywhere? if not, we should delete it

**Comment by samuelleolopes** [comment]
> old text "Watch Tutorial Videos"

ok, @kylembischof. The old text is not being used, I sent your request. Thanks.

**Review by kylembischof — APPROVED** [review]

**Comment by kylembischof** [comment]
ci:forward

**Comment by kylembischof** [comment]
@samuelleolopes can you remove the `/en-us` from the url per tiffany's request https://liferay.atlassian.net/browse/ISSD-3033?focusedCommentId=2611741

**Comment by samuelleolopes** [comment]
> @samuelleolopes can you remove the `/en-us` from the url per tiffany's request https://liferay.atlassian.net/browse/ISSD-3033?focusedCommentId=2611741

Hi @kylembischof, done!

**Comment by kylembischof** [comment]
ci:forward:force

**Comment by kylembischof** [comment]
ci:forward:force

**Pull request closed without merging**
