### PR TITLE
ISSD-3047 [PRM] [Impedibug] CSS doesn't work

### PR DESCRIPTION
**Pull request by eliasantosf**
Task: [ISSD-3047](https://liferay.atlassian.net/browse/ISSD-3047)

### CODE REVIEW

**Review by jairmedeiros — CHANGES_REQUESTED** [review]
I made some changes, but it need to test it

**Review by jairmedeiros — APPROVED** [review]

**Comment by jairmedeiros** [comment]
@thaynam take a look here pls!

**Review by thaynam — APPROVED** [review]
@jairmedeiros I added a configuration to the back button, in case there is no return url, (click in email link). We can set it manually in UAT

**Comment by thaynam** [comment]
[resent](https://github.com/liferay-customer-delivery/liferay-portal/pull/32)

**Pull request closed without merging**
