### PR TITLE
ISSD-3227 [PRM] [Impedibug] Correct exported fields from MDF request export

### PR DESCRIPTION
**Pull request by eliasantosf**
Task: [ISSD-3227](https://liferay.atlassian.net/browse/ISSD-3227)

### CODE REVIEW

**Review by jairmedeiros — APPROVED** [review]

**Comment by jairmedeiros** [comment]
ci:forward:force

**Comment by thaynam** [comment]
ci:stop

**Comment by thaynam** [comment]
this PR needs https://github.com/brianchandotcom/liferay-portal/pull/148398 merged to move forward

**Comment by eliasantosf** [comment]
Resent @thaynam

**Comment by eliasantosf** [comment]
ci:close

**Pull request closed without merging**
