### PR TITLE
ISSD-2873 [PRM] MDF Claim Edit page activity and expense cards to look clickable

### PR DESCRIPTION
**Pull request by abfranca**

### CODE REVIEW

**Comment by abfranca** [comment]
ci:test:sf

**Comment by abfranca** [comment]
ci:test:sf

**Review by jairmedeiros — APPROVED** [review]

**Review by kylembischof — APPROVED** [review]

**Comment by kylembischof** [comment]
ci:forward:force

**Comment by jairmedeiros** [comment]
ci:forward:force

**Comment by jairmedeiros** [comment]
ci:forward:force

**Comment by jairmedeiros** [comment]
ci:forward:force

**Pull request closed without merging**
