### PR TITLE
ISSD-2293 [CP 2.0] Release Notes page - Navigation and Hero Image

### PR DESCRIPTION
**Pull request by samuelleolopes**
[ISSD-2293](https://liferay.atlassian.net/browse/ISSD-2293)

### CODE REVIEW

**Comment by jennyhchen** [comment]
checked and changes asked from https://github.com/liferay-customer-delivery/liferay-portal/pull/8 was applied onto this pull

question @kylembischof / @jairmedeiros  is this commit correct? 
https://github.com/liferay-customer-delivery/liferay-portal/pull/17/commits/ad4a8fbf0deee72a48186ba415323b3605be61d8

Do we normally do translations like this? Seems like all previous code, translations are put into one page.json. Also, I know for sure, there shouldn't have been any 2023.Q1, 2023.Q2, 2023.Q3 quarterly releases as Support had removed it from production. Are these suppose to be dummy pages? Shouldn't we put 2024 pages instead?

**Comment by kylembischof** [comment]
@jennyhchen these are just creating the vocab naming, I don't think those need to be translated. But you are right about the old 2023 ones. 

@samuelleolopes you can remove the old 2023 vocab jsons, and just include 2024 Q1 and Q2 since those are the only relevant ones for now

**Comment by samuelleolopes** [comment]
@kylembischof, I've made a new commit with the change.

**Comment by kylembischof** [comment]
ci:test:sf

**Review by jairmedeiros — APPROVED** [review]

**Comment by kylembischof** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
ci:forward:force

**Pull request closed without merging**
